/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Tomas Lancheros
 */
public class FrmPrincipalCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipalCliente.class.getName());

    /**
     * Creates new form FrmPrincipalCliente
     */
    public FrmPrincipalCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRealizarServicio = new javax.swing.JButton();
        btnActualizarInformacion = new javax.swing.JButton();
        btnEliminarCuenta = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRealizarServicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRealizarServicio.setText("Solicitar servicio");

        btnActualizarInformacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnActualizarInformacion.setText("Actualizar información");

        btnEliminarCuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminarCuenta.setText("Eliminar cuenta");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblBienvenido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBienvenido.setText("Bienvenido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBienvenido)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizarInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRealizarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblBienvenido))
                .addGap(38, 38, 38)
                .addComponent(btnRealizarServicio)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarInformacion)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarCuenta)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnActualizarInformacion() {
        return btnActualizarInformacion;
    }

    public void setBtnActualizarInformacion(JButton btnActualizarInformacion) {
        this.btnActualizarInformacion = btnActualizarInformacion;
    }

    public JButton getBtnEliminarCuenta() {
        return btnEliminarCuenta;
    }

    public void setBtnEliminarCuenta(JButton btnEliminarCuenta) {
        this.btnEliminarCuenta = btnEliminarCuenta;
    }

    public JButton getBtnRealizarServicio() {
        return btnRealizarServicio;
    }

    public void setBtnRealizarServicio(JButton btnRealizarServicio) {
        this.btnRealizarServicio = btnRealizarServicio;
    }

    public JLabel getLblBienvenido() {
        return lblBienvenido;
    }

    public void setLblBienvenido(JLabel lblBienvenido) {
        this.lblBienvenido = lblBienvenido;
    }

    public JLabel getLblUsuario() {
        return lblUsuario;
    }

    public void setLblUsuario(JLabel lblUsuario) {
        this.lblUsuario = lblUsuario;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarInformacion;
    private javax.swing.JButton btnEliminarCuenta;
    private javax.swing.JButton btnRealizarServicio;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
