/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Tomas Lancheros
 */
public class FrmRealizarServicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRealizarServicio.class.getName());

    /**
     * Creates new form FrmRealizarServicio
     */
    public FrmRealizarServicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GbtnTipoServicio = new javax.swing.ButtonGroup();
        GbtnCategoria = new javax.swing.ButtonGroup();
        GbtnMetodoPago = new javax.swing.ButtonGroup();
        lblConductor = new javax.swing.JLabel();
        lblDireccionO = new javax.swing.JLabel();
        lblDireccionD = new javax.swing.JLabel();
        txtDireccionO = new javax.swing.JTextField();
        txtDireccionD = new javax.swing.JTextField();
        lblTipoServicio = new javax.swing.JLabel();
        rbtnPasajeros = new javax.swing.JRadioButton();
        rbtnAlimentos = new javax.swing.JRadioButton();
        cmbConductor = new javax.swing.JComboBox<>();
        lblDireccion = new javax.swing.JLabel();
        lblServicio = new javax.swing.JLabel();
        lblFechaTin = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        rbtnUrgente = new javax.swing.JRadioButton();
        rbtnNormal = new javax.swing.JRadioButton();
        rbtnEspecial = new javax.swing.JRadioButton();
        lblMetodoPago = new javax.swing.JLabel();
        rbtnBilleterasD = new javax.swing.JRadioButton();
        rbtnEfectivo = new javax.swing.JRadioButton();
        rbtnTarjetas = new javax.swing.JRadioButton();
        lblFecha = new javax.swing.JLabel();
        btnRealizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblConductor.setText("Elija el conductor para el servicio:");

        lblDireccionO.setText("Direccion origen:");

        lblDireccionD.setText("Direccion destino:");

        lblTipoServicio.setText("Tipo de servicio:");

        rbtnPasajeros.setText("Pasajeros");

        rbtnAlimentos.setText("Alimentos");

        lblDireccion.setText("Direccion:");

        lblServicio.setText("Solicitar servicio");

        lblFechaTin.setText("Fecha:");

        lblCategoria.setText("Elija la categoria del servicio:");

        rbtnUrgente.setText("Urgente");

        rbtnNormal.setText("Normal");

        rbtnEspecial.setText("Especial");

        lblMetodoPago.setText("Metodo de pago:");

        rbtnBilleterasD.setText("Billeteras digitales");

        rbtnEfectivo.setText("Efectivo");

        rbtnTarjetas.setText("Tarjetas (débito/crédito)");

        btnRealizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRealizar.setText("Realizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnBilleterasD)
                            .addComponent(rbtnTarjetas)
                            .addComponent(lblMetodoPago)
                            .addComponent(lblDireccion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDireccionO)
                                    .addComponent(txtDireccionO, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccionD, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblFechaTin)
                                            .addComponent(lblDireccionD))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFecha)))))
                        .addGap(0, 79, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoria)
                            .addComponent(lblServicio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnPasajeros)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnAlimentos))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbConductor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblConductor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnNormal)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnEspecial)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnUrgente))
                            .addComponent(lblTipoServicio)
                            .addComponent(rbtnEfectivo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(btnRealizar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblServicio)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoServicio)
                    .addComponent(lblFechaTin)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnPasajeros)
                    .addComponent(rbtnAlimentos))
                .addGap(18, 18, 18)
                .addComponent(lblConductor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionO)
                    .addComponent(lblDireccionD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnNormal)
                    .addComponent(rbtnUrgente)
                    .addComponent(rbtnEspecial))
                .addGap(18, 18, 18)
                .addComponent(lblMetodoPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnEfectivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnTarjetas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnBilleterasD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnRealizar)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ButtonGroup getGbtnCategoria() {
        return GbtnCategoria;
    }

    public void setGbtnCategoria(ButtonGroup GbtnCategoria) {
        this.GbtnCategoria = GbtnCategoria;
    }

    public ButtonGroup getGbtnMetodoPago() {
        return GbtnMetodoPago;
    }

    public void setGbtnMetodoPago(ButtonGroup GbtnMetodoPago) {
        this.GbtnMetodoPago = GbtnMetodoPago;
    }

    public ButtonGroup getGbtnTipoServicio() {
        return GbtnTipoServicio;
    }

    public void setGbtnTipoServicio(ButtonGroup GbtnTipoServicio) {
        this.GbtnTipoServicio = GbtnTipoServicio;
    }

    public JButton getBtnRealizar() {
        return btnRealizar;
    }

    public void setBtnRealizar(JButton btnRealizar) {
        this.btnRealizar = btnRealizar;
    }

    public JComboBox<String> getCmbConductor() {
        return cmbConductor;
    }

    public void setCmbConductor(JComboBox<String> cmbConductor) {
        this.cmbConductor = cmbConductor;
    }

    public JLabel getLblCategoria() {
        return lblCategoria;
    }

    public void setLblCategoria(JLabel lblCategoria) {
        this.lblCategoria = lblCategoria;
    }

    public JLabel getLblConductor() {
        return lblConductor;
    }

    public void setLblConductor(JLabel lblConductor) {
        this.lblConductor = lblConductor;
    }

    public JLabel getLblDireccion() {
        return lblDireccion;
    }

    public void setLblDireccion(JLabel lblDireccion) {
        this.lblDireccion = lblDireccion;
    }

    public JLabel getLblDireccionD() {
        return lblDireccionD;
    }

    public void setLblDireccionD(JLabel lblDireccionD) {
        this.lblDireccionD = lblDireccionD;
    }

    public JLabel getLblDireccionO() {
        return lblDireccionO;
    }

    public void setLblDireccionO(JLabel lblDireccionO) {
        this.lblDireccionO = lblDireccionO;
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public void setLblFecha(JLabel lblFecha) {
        this.lblFecha = lblFecha;
    }

    public JLabel getLblFechaTin() {
        return lblFechaTin;
    }

    public void setLblFechaTin(JLabel lblFechaTin) {
        this.lblFechaTin = lblFechaTin;
    }

    public JLabel getLblMetodoPago() {
        return lblMetodoPago;
    }

    public void setLblMetodoPago(JLabel lblMetodoPago) {
        this.lblMetodoPago = lblMetodoPago;
    }

    public JLabel getLblServicio() {
        return lblServicio;
    }

    public void setLblServicio(JLabel lblServicio) {
        this.lblServicio = lblServicio;
    }

    public JLabel getLblTipoServicio() {
        return lblTipoServicio;
    }

    public void setLblTipoServicio(JLabel lblTipoServicio) {
        this.lblTipoServicio = lblTipoServicio;
    }

    public JRadioButton getRbtnAlimentos() {
        return rbtnAlimentos;
    }

    public void setRbtnAlimentos(JRadioButton rbtnAlimentos) {
        this.rbtnAlimentos = rbtnAlimentos;
    }

    public JRadioButton getRbtnBilleterasD() {
        return rbtnBilleterasD;
    }

    public void setRbtnBilleterasD(JRadioButton rbtnBilleterasD) {
        this.rbtnBilleterasD = rbtnBilleterasD;
    }

    public JRadioButton getRbtnEfectivo() {
        return rbtnEfectivo;
    }

    public void setRbtnEfectivo(JRadioButton rbtnEfectivo) {
        this.rbtnEfectivo = rbtnEfectivo;
    }

    public JRadioButton getRbtnEspecial() {
        return rbtnEspecial;
    }

    public void setRbtnEspecial(JRadioButton rbtnEspecial) {
        this.rbtnEspecial = rbtnEspecial;
    }

    public JRadioButton getRbtnNormal() {
        return rbtnNormal;
    }

    public void setRbtnNormal(JRadioButton rbtnNormal) {
        this.rbtnNormal = rbtnNormal;
    }

    public JRadioButton getRbtnPasajeros() {
        return rbtnPasajeros;
    }

    public void setRbtnPasajeros(JRadioButton rbtnPasajeros) {
        this.rbtnPasajeros = rbtnPasajeros;
    }

    public JRadioButton getRbtnTarjetas() {
        return rbtnTarjetas;
    }

    public void setRbtnTarjetas(JRadioButton rbtnTarjetas) {
        this.rbtnTarjetas = rbtnTarjetas;
    }

    public JRadioButton getRbtnUrgente() {
        return rbtnUrgente;
    }

    public void setRbtnUrgente(JRadioButton rbtnUrgente) {
        this.rbtnUrgente = rbtnUrgente;
    }

    public JTextField getTxtDireccionD() {
        return txtDireccionD;
    }

    public void setTxtDireccionD(JTextField txtDireccionD) {
        this.txtDireccionD = txtDireccionD;
    }

    public JTextField getTxtDireccionO() {
        return txtDireccionO;
    }

    public void setTxtDireccionO(JTextField txtDireccionO) {
        this.txtDireccionO = txtDireccionO;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GbtnCategoria;
    private javax.swing.ButtonGroup GbtnMetodoPago;
    private javax.swing.ButtonGroup GbtnTipoServicio;
    private javax.swing.JButton btnRealizar;
    private javax.swing.JComboBox<String> cmbConductor;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblConductor;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccionD;
    private javax.swing.JLabel lblDireccionO;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaTin;
    private javax.swing.JLabel lblMetodoPago;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblTipoServicio;
    private javax.swing.JRadioButton rbtnAlimentos;
    private javax.swing.JRadioButton rbtnBilleterasD;
    private javax.swing.JRadioButton rbtnEfectivo;
    private javax.swing.JRadioButton rbtnEspecial;
    private javax.swing.JRadioButton rbtnNormal;
    private javax.swing.JRadioButton rbtnPasajeros;
    private javax.swing.JRadioButton rbtnTarjetas;
    private javax.swing.JRadioButton rbtnUrgente;
    private javax.swing.JTextField txtDireccionD;
    private javax.swing.JTextField txtDireccionO;
    // End of variables declaration//GEN-END:variables
}
